// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:815622fb-128f-4b35-955b-0fd760d221a9',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': 'a265e38be6e747ff8319cc0ff209419f',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '3eedc9a0-4d77-4fc7-a447-8db419533392',
    'aws_project_name': 'potluck-driver',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'potluckdriver-mobilehub-596578573',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'potluckdriver-userfiles-mobilehub-596578573',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_JaclOXWNj',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '6dbftrfq6lqsojnl2c59dvn8eb',
}

export default awsmobile;
